apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment #The name of the Kubernetes 
        #Deployment to be created in the Kubernetes cluster
  labels:
    app: jobhaven-app
spec:
  replicas: 2 #The number of pods to be created in the 
    #Kubernetes cluster for the application container
  selector:
    matchLabels:
      app: jobhaven-app
  template:
    metadata:
      labels:
        app: jobhaven-app 
    spec:
      containers:
      - name: jobhaven-app #The name of application container
        #The Docker image for building the application container
        image: dan7467/jobhaven-app:latest 
        ports:
        - containerPort: 3000 #The port for the application container